baseurl = "https://lisa-coes.netlify.app/"
title = "Laboratorio de Ciencia Social Abierta"
theme = "hugo-universal-theme"
languageCode = "es-cl"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "" #codigo G

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Ciencia social abierta"
    url  = "/" 
    weight = 1

[[menu.main]]
    parent = "home"
    name = "¿Qué es ciencia abierta?"
    url = "/02novedades/"
    weight = 1

[[menu.main]]
    parent = "home"
    name = "Colaboraciones"
    url = "/equipo/"
    weight = 2


[[menu.main]]
    parent = "home"
    name = "Contáctanos"
    url = "/contacto/"
    weight = 4

#-------------------------
[[menu.main]]
    identifier = "blog"
    name = "Componentes"
    url  = "/categories/componentes/"
    weight = 2

[[menu.main]]
    parent = "blog"
    name = "0. Introducción"
    url = "/00intro-componentes/"

[[menu.main]]
    parent = "blog"
    name = "1. Diseño Transparente"
    url = "/01componentes/"

[[menu.main]]
    parent = "blog"
    name = "2. Datos Abiertos"
    url = "/02componentes/"

[[menu.main]]
    parent = "blog"
    name = "3. Análisis reproducible"
    url = "/03componentes/"

[[menu.main]]
    parent = "blog"
    name = "4. Publicaciones libres"
    url = "/04componentes/"

#-------------------------
[[menu.main]]
    identifier = "news"
    name = "Interés"
    url  = "/links"
    weight = 3

[[menu.main]]
    parent = "news"
    name = "Links"
    url  = "/links"
    weight = 1

[[menu.main]]
    parent = "news"
    name = "Novedades"
    url  = "https://lisa-coes.netlify.app/categories/novedades/"
    weight = 2


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/lisa-coes/"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com/coes2020"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/CentroCOES"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:lisa@coes.cl"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "LISA"
    defaultKeywords = ["lisa", "coes"]
    mainSections = ["blog"]
    defaultDescription = "Sitio desarrollado por valentinaandrade"

    # Social media
    facebook_site = "coes2020" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "CentroCOES" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "red"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "f/mwkwapba"
    contact_form_ajax = false

    about_us = "<p>Laboratorio Ciencia Social Abierta, COES</p>"
    copyright = "Copyright (c) 2020 - 2021, Laboratorio Ciencia Social Abierta; todos los derechos reservados."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><strong>COES</strong>
        <br>13/25 Diagonal Paraguay 257
        <br>Torre 26, Oficina 1504
        <br>Santiago-RM
        <br>Chile
        <br>
      </p>
      """

[Permalinks]
    blog = "/:filename/"
#"/blog/:year/:month/:day/:filename/"
# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contáctenos en lisa@coes.cl</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
 
[params.test]
    enable = true
    title = "LISA"
    subtitle = "El **Laboratorio de Ciencia Social Abierta** es una iniciativa del *Centro de Estudios de Conflicto y Cohesión Social* (COES) que tiene como propósito ser una guía para el desarrollo de una ciencia social abierta y reproducible para la comunidad científica y la ciudadanía. Nos enfocamos en promover y construir **herramientas de los cuatro componentes** principales de la ciencia abierta: *(1) diseño transparente, (2) apertura de datos, (3) análisis reproducibles y (4) publicaciones libres*."

[params.features]
    enable = true
    cols = 4
    title = "Pasos para una Ciencia Abierta"
    subtitle = "Presiona cada uno de ellos para conocer más detalles"
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
 
[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Equipo"
    
[params.see_more]
    enable = false
    icon = "fas fa-chart-line"
    title = "**Guía para la apertura de datos**"
    subtitle = ""
    link_url = "/02componentes/"
    link_text = "¡Quiero aprender!"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = ""
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "novedades"
    subtitle = "¿Quieres saber más sobre Ciencia Social Abierta?"
